package biometricauthentication;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author TK
 */
public class MainWindow extends javax.swing.JFrame {

    private int preX;
    private int preY;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        photoPanel = new javax.swing.JPanel();
        photoLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        thumbText = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        indexText = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        middleText = new javax.swing.JTextField();
        jCheckBox4 = new javax.swing.JCheckBox();
        ringText = new javax.swing.JTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        pinkyText = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nameText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hand Geometric Authentication");

        jButton1.setText("Add Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        photoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photoPanelLayout.createSequentialGroup()
                .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Thumb");

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("Index Finger");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setText("Middle Finger");

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setText("Ring Finger");

        ringText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ringTextActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox5);
        jCheckBox5.setText("Pinky");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Authenticate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(indexText)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(middleText, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(ringText)
                                    .addComponent(pinkyText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(thumbText, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nameText)
                                .addGap(18, 18, 18)
                                .addComponent(saveBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(thumbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(indexText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox3)
                            .addComponent(middleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox4)
                            .addComponent(ringText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(pinkyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this); //Where frame is the parent component

        File file = null;
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            try {
                photoLabel.setIcon(new ImageIcon(new ImageIcon(ImageIO.read(file)).getImage().getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(), photoLabel.getWidth())));
            } catch (IOException e) {
                e.printStackTrace();
            }
            System.out.println(file.getAbsoluteFile());
            //JLabel imgLabel = new JLabel(file.getAbsolutePath());
            // photoPanel.add(imgLabel);
            photoPanel.revalidate();
            photoPanel.repaint();
            //Now you have your file to do whatever you want to do
        } else {
            //User did not choose a valid file
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void ringTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ringTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ringTextActionPerformed

    private void photoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoLabelMouseClicked
        if (!"null".equals(getSelectedBtn())) {
            System.out.println(getSelectedBtn());
            if (preX != 0) {
                double distance = Math.hypot(preX - evt.getX(), preY - evt.getY());
                System.out.println(distance);
                getField(getSelectedBtn().toLowerCase()).setText(distance + "");
                preX = 0;
                preY = 0;
            } else {
                preX = evt.getX();
                preY = evt.getY();
            }
        }

    }//GEN-LAST:event_photoLabelMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        System.out.println("action controller");
//Read Student array from file.
        User user=new User(nameText.getText(), Double.parseDouble(thumbText.getText()),Double.parseDouble(indexText.getText()), Double.parseDouble(middleText.getText()), Double.parseDouble(ringText.getText()), Double.parseDouble(pinkyText.getText()));
        ArrayList<User> users=getUsers();
        
        if(users == null){
            users=new ArrayList<>();
            users.add(user);
            System.out.println("no array");
            
        }else{
            users.add(user);
            System.out.println("got array");
        }
        for (User user1 : users) {
                System.out.println(user1.getName());
            }
        
        saveUser(users);
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private ArrayList<User> getUsers(){
        ArrayList<User> users=null;
        try{
            FileInputStream fis = new FileInputStream("users.ser");
        ObjectInputStream ois = new ObjectInputStream(fis);
        users= (ArrayList<User>) ois.readObject();
        ois.close();
        //Student[] studentsFromSavedFile = (Student[]) ois.readObject();
        
        }catch (FileNotFoundException ex) {
            //Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
           // Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
           // Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return users;
    }
    
    private void saveUser(ArrayList<User> users){
        FileOutputStream fos = null;
        try {
            fos = new FileOutputStream("users.ser");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(users);
            oos.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fos.close();
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        User user=new User(nameText.getText(), Double.parseDouble(thumbText.getText()),Double.parseDouble(indexText.getText()), Double.parseDouble(middleText.getText()), Double.parseDouble(ringText.getText()), Double.parseDouble(pinkyText.getText()));
        String message=authenticateUser(user, getUsers());
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jButton3ActionPerformed

    private String authenticateUser(User user, ArrayList<User> users){
        String userList="";
        for (User user1 : users) {
            double thumbRatio=user.getThumb()/user1.getThumb();
            double indexRatio=user.getIndex()/user1.getIndex();
            double middleRatio=user.getMiddle()/user1.getMiddle();
            double ringRatio=user.getRing()/user1.getRing();
            double pinkyRatio=user.getPinky()/user1.getPinky();
            
            double totalThumbratio= (thumbRatio/indexRatio)+(thumbRatio/middleRatio)+(thumbRatio/ringRatio)+(thumbRatio/pinkyRatio);
            double totalindexratio= (thumbRatio/indexRatio)+(indexRatio/middleRatio)+(indexRatio/ringRatio)+(indexRatio/pinkyRatio);
            double totalmiddleratio= (middleRatio/thumbRatio)+(middleRatio/indexRatio)+(middleRatio/ringRatio)+(middleRatio/pinkyRatio);
            double totalringratio= (ringRatio/indexRatio)+(ringRatio/middleRatio)+(ringRatio/thumbRatio)+(ringRatio/pinkyRatio);
            double totalpinkyratio= (pinkyRatio/indexRatio)+(pinkyRatio/middleRatio)+(pinkyRatio/thumbRatio)+(pinkyRatio/ringRatio);
            System.out.println(totalThumbratio+" "+totalindexratio+" "+totalmiddleratio+" "+totalpinkyratio+" "+totalringratio);
            
            double ratio=(totalThumbratio+totalindexratio+totalmiddleratio+totalpinkyratio+totalringratio)/20; 
            System.out.println(ratio);
            if (ratio>0.98 && ratio< 1.02){
                //userList+=" "+user1.getName();
                return "User : "+user1.getName();
                
                //JOptionPane.showMessageDialog(this, "User : "+user1.getName());
            }
       }
       // return userList;
        return "Authentication fail";
        
        
    }
    private JTextField getField(String name) {
        switch (name) {
            case "thumb":
                return thumbText;
            case "middle finger":
                return middleText;
            case "index finger":
                return indexText;
            case "ring finger":
                return ringText;
            case "pinky":
                return pinkyText;
        }
        return null;
    }

    private String getSelectedBtn() {
        for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "null";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField indexText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField middleText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JTextField pinkyText;
    private javax.swing.JTextField ringText;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField thumbText;
    // End of variables declaration//GEN-END:variables
}
